### ISSUE TITLE
problem with jumping snippet handle

### ISSUE THREAD

**Issue by sepehr09** [Kademi/keditor#137]
i try my best to show the problem in the GIF below:
(gif size: 3.2 MB)

![bug](https://user-images.githubusercontent.com/11753906/48662038-22373100-ea91-11e8-89bc-c09f55ba2e5a.gif)

as you can see handle is jumping from mouse position when surfing from right container to left container!
(surf from left container to right container is ok! )

**Comment by ducdhm** [comment]
Thanks @sepehr09. I'll investigate and try to resolve this issue. Not sure it's bug of jquery or css stuff or keditor stuff.

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
@sepehr09 can you test with `test.html` file inside `src` folder? Please make sure you run `gulp dev` before testing.

**Comment by sepehr09** [comment]
thanks @ducdhm
i tested but the problem is still there:

![1](https://user-images.githubusercontent.com/11753906/48758347-fc8a7180-ecb4-11e8-8593-1e307a095c1d.gif)

this is google chrome console debug result :

**NORMAL:**
![1](https://user-images.githubusercontent.com/11753906/48757981-c1d40980-ecb3-11e8-84f7-8ecc413f073e.jpg)

**PROBLEM:** when surf from right container to left container and then go out of both :
![2](https://user-images.githubusercontent.com/11753906/48758013-ddd7ab00-ecb3-11e8-8f8b-09618af7ab81.jpg)
the snippet stuck at container even when drag out of it's area.

**Comment by ducdhm** [comment]
@sepehr09 I have tested with jQuery-UI only. Seems like it's jQuery-UI issue, not KEditor. So I'll closed this issue as `invalid`.

Btw, you can start use KEditor Gen 2 (in `gen-2` branch) with more stability, options and etc...

FYI: JSFiddle link for this issue with only jQuery-UI is [here](https://jsfiddle.net/bobkhin/14nvduam/)
