### ISSUE TITLE
Bug in containers settings

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#182]
steps:
1.add a container-4 columns(25%-25%-25%25%)
2.in each sub container add a container-1 column.
3. now change the background color of each container inside the sub containers.(start from left). when you reach the right container the color in all the containers will be changed.

**the right most container(inside the subcontainer) settings is over lapped by the whole container settings**
![image](https://user-images.githubusercontent.com/41923272/60783009-59646a80-a166-11e9-9b21-a04e2c0dd23b.png)
![image](https://user-images.githubusercontent.com/41923272/60783034-71d48500-a166-11e9-8dbd-7a100db3c6c1.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by srikanthmovva** [comment]
no, i still see the whole container settings is overlapping the sub container settings. Try adding background color to only first subcontainer.
![image](https://user-images.githubusercontent.com/41923272/60971279-68534480-a341-11e9-8049-9f4d6ba99308.png)

**Comment by ducdhm** [comment]
@srikanthmovva It's toolbar for container, not sub-container side. At the moment, it's very simple demo for container setting. So if you inspect HTML element, you'll see toolbar for container and first sub-container are overlap
